sitename: tinyGAMES.fun - hyper casual games studio
slogan: We Create TinyGames for \Big Moments of Mega Fun!
description: We Create TinyGames for Big Moments of Mega Fun!
keywords: games,tiny games,hypercasual,casual games,mobile games,instant games
